name: release

on:
    push:
        tags:
            - 'v*'
permissions:
    contents: write

env:
    CARGO_TERM_COLOR: always

jobs:
    linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install target
              run: rustup target add x86_64-unknown-linux-gnu
            - name: Build
              run: cargo build --release --target=x86_64-unknown-linux-gnu
            - name: Upload binary
              uses: actions/upload-artifact@v4
              with:
                  name: Image-to-Ascii
                  path: target/x86_64-unknown-linux-gnu/release/Image-to-Ascii

    release:
        needs: [linux]
        runs-on: ubuntu-latest

        steps:
            - name: Download binaries
              uses: actions/download-artifact@v4
            - name: list files
              run: find
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                  name: ${{  github.ref_name }}
                  tag: ${{ github.ref_name }}
                  artifacts: 'Image-to-Ascii/*'
